name: Build Fly Brain Bridge

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: Win64
          sdk: v5.10.1

      - uses: actions/upload-artifact@v4
        with:
          name: flybrain-bridge
          path: ${{ steps.build.outputs.build-output }}
